services:
  api:
    build:
      context: ./api
    container_name: api
    env_file:
      - ./api/.env
    environment:
      # puedes sobreescribir aquí si quieres, pero con .env es suficiente
      PORT: 3000
    ports:
      - "4010:3000"  # API: http://localhost:4010
    networks:
      - sf_net

  frontend:
    image: nginx:alpine
    container_name: sequence-filter-frontend
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
    ports:
      - "9091:80"     # Front: http://localhost:9091
    networks:
      - sf_net

networks:
  sf_net:
    driver: bridge
